/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;


/**
 *
 * @author daniel davila
 */

import java.awt.Image;
import java.awt.Toolkit;
import java.sql.Connection;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class ControlIngresoView extends javax.swing.JFrame {
    /**
     * Creates new form VentanaPrincipal
     */
    public ControlIngresoView() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.getIconImage();
    }

    /**
     *
     * @return
     */
    @Override
    public final Image getIconImage(){
        Image iconoApp=Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("utils/imgs/icono.jpg"));
        return iconoApp;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonSalir = new javax.swing.JButton();
        panelConexion = new javax.swing.JPanel();
        labelUsuario = new javax.swing.JLabel();
        labelHost = new javax.swing.JLabel();
        labelContraseña = new javax.swing.JLabel();
        labelPuerto = new javax.swing.JLabel();
        labelDB = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        txtHost = new javax.swing.JTextField();
        txtPuerto = new javax.swing.JTextField();
        txtDB = new javax.swing.JTextField();
        txtContrasena = new javax.swing.JPasswordField();
        tituloConexion = new javax.swing.JLabel();
        botonConectarDB = new javax.swing.JButton();
        labelConexion = new javax.swing.JLabel();
        labelLogo = new javax.swing.JLabel();
        tituloP1 = new javax.swing.JLabel();
        tituloP2 = new javax.swing.JLabel();
        labelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName("ventanaPrincipal"); // NOI18N
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/salir.png"))); // NOI18N
        buttonSalir.setBorderPainted(false);
        buttonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(buttonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 0, 20, 20));

        panelConexion.setBackground(new java.awt.Color(153, 153, 153));

        labelUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        labelUsuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelUsuario.setText("Usuario:");

        labelHost.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        labelHost.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelHost.setText("Host:");

        labelContraseña.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        labelContraseña.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelContraseña.setText("Contraseña:");

        labelPuerto.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        labelPuerto.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelPuerto.setText("Puerto:");

        labelDB.setFont(new java.awt.Font("Gill Sans MT", 0, 18)); // NOI18N
        labelDB.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelDB.setText("Base Datos:");

        txtUsuario.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtUsuario.setText("root");
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        txtHost.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtHost.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHost.setText("localhost");
        txtHost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtHostActionPerformed(evt);
            }
        });

        txtPuerto.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtPuerto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtPuerto.setText("3306");
        txtPuerto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPuertoActionPerformed(evt);
            }
        });

        txtDB.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        txtDB.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtDB.setText("Reto5_BaseDatos");
        txtDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDBActionPerformed(evt);
            }
        });

        txtContrasena.setText("daniel980903");

        tituloConexion.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        tituloConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloConexion.setText("CONEXIÓN CON LA BASE DE DATOS");

        botonConectarDB.setBackground(new java.awt.Color(204, 240, 224));
        botonConectarDB.setFont(new java.awt.Font("Gill Sans MT", 0, 14)); // NOI18N
        botonConectarDB.setText("Conectar");
        botonConectarDB.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                botonConectarDBMouseMoved(evt);
            }
        });
        botonConectarDB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonConectarDBActionPerformed(evt);
            }
        });

        labelConexion.setForeground(new java.awt.Color(255, 0, 0));
        labelConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelConexionLayout = new javax.swing.GroupLayout(panelConexion);
        panelConexion.setLayout(panelConexionLayout);
        panelConexionLayout.setHorizontalGroup(
            panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConexionLayout.createSequentialGroup()
                .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConexionLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panelConexionLayout.createSequentialGroup()
                                    .addGap(10, 10, 10)
                                    .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConexionLayout.createSequentialGroup()
                                            .addComponent(labelUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtUsuario))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConexionLayout.createSequentialGroup()
                                            .addComponent(labelHost, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtHost))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConexionLayout.createSequentialGroup()
                                            .addComponent(labelPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtPuerto))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConexionLayout.createSequentialGroup()
                                            .addComponent(labelDB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelConexionLayout.createSequentialGroup()
                                    .addComponent(labelContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(txtContrasena)))
                            .addGroup(panelConexionLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(tituloConexion))))
                    .addGroup(panelConexionLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(botonConectarDB, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConexionLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(labelConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConexionLayout.setVerticalGroup(
            panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConexionLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(tituloConexion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelConexionLayout.createSequentialGroup()
                        .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelUsuario)
                            .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelHost)
                            .addComponent(txtHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelPuerto)
                            .addComponent(txtPuerto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelDB))
                    .addComponent(txtDB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelConexionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtContrasena, javax.swing.GroupLayout.DEFAULT_SIZE, 21, Short.MAX_VALUE)
                    .addComponent(labelContraseña))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botonConectarDB)
                .addGap(18, 18, 18)
                .addComponent(labelConexion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        getContentPane().add(panelConexion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 290, 300));

        labelLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/teRetoAProgramarlo.png"))); // NOI18N
        getContentPane().add(labelLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 290, 70));

        tituloP1.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        tituloP1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloP1.setText("Sistema de control");
        getContentPane().add(tituloP1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 50));
        tituloP1.getAccessibleContext().setAccessibleName("Sistema de control de \nRegistros de Bibliotecas");

        tituloP2.setFont(new java.awt.Font("Gill Sans MT", 0, 24)); // NOI18N
        tituloP2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloP2.setText("de registros de Bibliotecas");
        getContentPane().add(tituloP2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 330, 40));

        labelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/imgs/fondo.png"))); // NOI18N
        getContentPane().add(labelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 510));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_buttonSalirActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed

    private void txtHostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtHostActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtHostActionPerformed

    private void txtPuertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPuertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPuertoActionPerformed

    private void txtDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDBActionPerformed

    private void botonConectarDBMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_botonConectarDBMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_botonConectarDBMouseMoved

    private void botonConectarDBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonConectarDBActionPerformed
        Connection conn=controller.ControlIngresoController.eventoBotonConectarDB();
        if (null != conn){
            controller.ControlIngresoController.ocultar();
            controller.vistaVentanaController.mostrar();
        }
        else {
            labelConexion.setText("Datos incorrectos intente de nuevo*");      
        }
    }//GEN-LAST:event_botonConectarDBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ControlIngresoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new ControlIngresoView().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonConectarDB;
    private javax.swing.JButton buttonSalir;
    private javax.swing.JLabel labelConexion;
    private javax.swing.JLabel labelContraseña;
    private javax.swing.JLabel labelDB;
    private javax.swing.JLabel labelFondo;
    private javax.swing.JLabel labelHost;
    private javax.swing.JLabel labelLogo;
    private javax.swing.JLabel labelPuerto;
    private javax.swing.JLabel labelUsuario;
    private javax.swing.JPanel panelConexion;
    private javax.swing.JLabel tituloConexion;
    private javax.swing.JLabel tituloP1;
    private javax.swing.JLabel tituloP2;
    private javax.swing.JPasswordField txtContrasena;
    private javax.swing.JTextField txtDB;
    private javax.swing.JTextField txtHost;
    private javax.swing.JTextField txtPuerto;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables

    
    //Capturar datos de entrada
    public JPasswordField getTxtContrasena() {
        return txtContrasena;
    }

    public JTextField getTxtDB() {
        return txtDB;
    }

    public JTextField getTxtHost() {
        return txtHost;
    }

    public JTextField getTxtPuerto() {
        return txtPuerto;
    }

    public JTextField getTxtUsuario() {
        return txtUsuario;
    }

    
}
